const KEY='caredesk_demo_v1';let S=JSON.parse(localStorage.getItem(KEY)||'null')||SEED();
const P=new URLSearchParams(location.search);const HN=P.get('h')||localStorage.getItem('cd_h')||'Demo Specialist Hospital';localStorage.setItem('cd_h',HN);
document.getElementById('hname').textContent=HN;document.title='CareDesk | '+HN;
let online=true,pending=0,view='dash',cur=null;
const $=s=>document.querySelector(s),N=n=>'₦'+Number(n).toLocaleString('en-NG'),today=new Date().toISOString().slice(0,10);
const now=()=>{const d=new Date();return d.toISOString().slice(0,10)+' '+d.toTimeString().slice(0,5)};
const ROLES={Admin:['dash','patients','appts','lab','pharm','bill','wa','audit'],'Records officer':['patients','appts','bill'],Nurse:['patients','appts','wa'],Doctor:['dash','patients','appts','lab','pharm'],Cashier:['bill','patients'],'Lab scientist':['lab','patients'],Pharmacist:['pharm','patients']};
const WHO={Admin:'Medical Director','Records officer':'Records (Grace)',Nurse:'Nurse Ruth',Doctor:'Dr. Ibe',Cashier:'Cashier (Tolu)','Lab scientist':'Lab (Sam)',Pharmacist:'Pharmacy (Kemi)'};
const LAB={dash:'Dashboard',patients:'Patients',appts:'Appointments & queue',lab:'Laboratory',pharm:'Pharmacy',bill:'Billing & payments',wa:'WhatsApp messages',audit:'Audit log'};
let role=localStorage.getItem('cd_role')||'Admin';
$('#role').innerHTML=Object.keys(ROLES).map(r=>`<option ${r==role?'selected':''}>${r}</option>`).join('');
$('#role').onchange=e=>{role=e.target.value;localStorage.setItem('cd_role',role);log('Signed in as '+role);view=ROLES[role][0];render();toast('Now viewing as '+role+'. Menu shows only what this role may see.')};
function save(){localStorage.setItem(KEY,JSON.stringify(S));if(!online){pending++;$('#pend').textContent=pending}}
function log(a){S.audit.unshift({t:now(),who:WHO[role],a});save()}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(t._h);t._h=setTimeout(()=>t.classList.remove('show'),3200)}
function modal(h){$('#mbox').innerHTML=h;$('#modal').classList.add('show')}function close_(){$('#modal').classList.remove('show')}
$('#modal').onclick=e=>{if(e.target.id=='modal')close_()};
$('#net').onclick=()=>{online=!online;const b=$('#net');b.classList.toggle('off',!online);b.innerHTML=online?'&#9679; Online':'&#9675; Offline';$('#offban').classList.toggle('show',!online);if(online&&pending){toast(pending+' change(s) synced to the hospital server.');pending=0}else if(!online)toast('Network dropped. Keep working, nothing is lost.')};
$('#reset').onclick=e=>{e.preventDefault();if(confirm('Reset demo data?')){S=SEED();save();render();toast('Demo reset.')}};
const pt=id=>S.patients.find(p=>p.id==id)||{name:'?'};const age=d=>Math.floor((Date.now()-new Date(d))/31557600000);
function wa(pid,msg){S.wa.unshift({to:pid,msg,t:now()});save()}
function norm(s){return s.toLowerCase().replace(/[^a-z0-9]/g,'')}
function lev(a,b){const m=[];for(let i=0;i<=b.length;i++)m[i]=[i];for(let j=0;j<=a.length;j++)m[0][j]=j;for(let i=1;i<=b.length;i++)for(let j=1;j<=a.length;j++)m[i][j]=b[i-1]==a[j-1]?m[i-1][j-1]:Math.min(m[i-1][j-1]+1,m[i][j-1]+1,m[i-1][j]+1);return m[b.length][a.length]}
function match(p,q){q=norm(q);if(!q)return true;const f=[p.name,p.phone,p.id].map(norm);if(f.some(x=>x.includes(q)))return true;return p.name.toLowerCase().split(' ').some(w=>q.length>2&&lev(norm(w),q)<=Math.max(1,Math.floor(q.length/4)))}
function nav(){$('#nav').innerHTML=ROLES[role].map(v=>`<button class="${v==view||(view=='pt'&&v=='patients')||(view=='reg'&&v=='patients')?'on':''}" onclick="go('${v}')">${LAB[v]}</button>`).join('')}
function go(v,id){view=v;cur=id||null;render();scrollTo(0,0)}
function render(){nav();$('#main').innerHTML=(V[view]||V.dash)()}
const V={};
V.dash=()=>{const tb=S.bills.filter(b=>b.d==today),col=tb.reduce((a,b)=>a+b.paid,0),owed=S.bills.reduce((a,b)=>a+(tot(b)-b.paid),0),q=S.appts.filter(a=>a.date==today);S.rev[6]=col;const mx=Math.max(...S.rev,1),days=['Thu','Fri','Sat','Sun','Mon','Tue','Today'];
const low=S.stock.filter(s=>s.qty<30||dleft(s.exp)<60);
return `<h2>Good day, ${WHO[role]}</h2><div class="grid">
<div class="kpi"><b>${q.length}</b><span>Patients booked today</span></div><div class="kpi"><b>${N(col)}</b><span>Collected today</span></div>
<div class="kpi"><b>${N(owed)}</b><span>Outstanding bills</span></div><div class="kpi"><b>${S.patients.length}</b><span>Patients on record</span></div>
<div class="kpi"><b>${S.labs.filter(l=>l.status=='Pending').length}</b><span>Lab tests pending</span></div><div class="kpi"><b style="color:${low.length?'var(--red)':'var(--acc)'}">${low.length}</b><span>Drugs low or near expiry</span></div></div>
<div class="card"><h3>Revenue, last 7 days</h3><div class="bars">${S.rev.map((r,i)=>`<div style="height:${Math.max(4,r/mx*100)}%"><em>${r?Math.round(r/1000)+'k':''}</em><span>${days[i]}</span></div>`).join('')}</div><div style="height:22px"></div></div>
<div class="card"><h3>Today's queue</h3><div class="list">${q.map(a=>`<div class="it"><div><div class="t">${a.time} &middot; ${pt(a.pid).name}</div><div class="s">${a.clinic} &middot; ${a.doc}</div></div><span class="tag ${a.status=='Waiting'?'amb':a.status=='With doctor'?'acc':a.status=='Done'?'grn':''}">${a.status}</span></div>`).join('')||'<p class="muted">No one booked.</p>'}</div></div>
${low.length?`<div class="card"><h3>Pharmacy alerts</h3>${low.map(s=>`<div class="s">${s.drug}: ${s.qty} left${dleft(s.exp)<60?`, expires in ${dleft(s.exp)} days`:''}</div>`).join('')}</div>`:''}`};
const dleft=e=>Math.round((new Date(e)-Date.now())/86400000);const tot=b=>b.items.reduce((a,i)=>a+i[1],0);
V.patients=()=>`<h2>Find a patient</h2><div class="card"><input id="q" placeholder="Type a name, phone number or hospital number..." oninput="srch()" autofocus>
<p class="muted">Try "adaeze", "0805", "DSH-1003" or even a misspelling like "Emika".</p><div class="list" id="res">${plist('')}</div></div>
${role=='Records officer'||role=='Admin'?`<button class="btn" onclick="go('reg')">+ Register new patient</button>`:''}`;
function plist(q){const r=S.patients.filter(p=>match(p,q));return r.map(p=>`<div class="it" onclick="openP('${p.id}')" style="cursor:pointer"><div><div class="t">${p.name} ${p.allergies.length?'<span class="tag red">Allergy</span>':''} ${p.hmo?'<span class="tag acc">'+p.hmo+'</span>':''}</div><div class="s">${p.id} &middot; ${p.phone} &middot; ${p.sex}, ${age(p.dob)} yrs</div></div><span class="btn sm sec">Open</span></div>`).join('')||'<p class="muted">No match. Register them as a new patient.</p>'}
function srch(){$('#res').innerHTML=plist($('#q').value)}
function openP(id){log('Opened record '+id);go('pt',id)}
V.pt=()=>{const p=pt(cur),ev=[...p.events].reverse(),b=S.bills.filter(x=>x.pid==p.id),canClin=['Doctor','Nurse','Admin'].includes(role),isDoc=['Doctor','Admin'].includes(role);
const clinical=role!='Cashier';
return `<button class="btn sm sec" onclick="go('patients')">&larr; Back</button><div class="card" style="margin-top:10px"><h2 style="margin-bottom:4px">${p.name}</h2>
<div class="muted">${p.id} &middot; ${p.sex}, ${age(p.dob)} yrs &middot; Blood group ${p.blood} &middot; ${p.phone}${p.hmo?' &middot; HMO: '+p.hmo:''}</div>
${p.allergies.length&&clinical?`<div class="allergy">&#9888; Allergic to: ${p.allergies.join(', ')}</div>`:''}<div class="muted">Next of kin: ${p.nok} &middot; Consent on file: ${p.consent?'Yes':'No'}</div>
<div class="row" style="margin-top:10px">${canClin?`<button class="btn sm" onclick="vitals()">Record vitals</button>`:''}${isDoc?`<button class="btn sm" onclick="consult()">Consultation note</button><button class="btn sm" onclick="labreq()">Request lab test</button><button class="btn sm" onclick="presc()">Prescribe</button>`:''}${['Records officer','Admin','Nurse'].includes(role)?`<button class="btn sm sec" onclick="book('${p.id}')">Book appointment</button>`:''}</div></div>
${clinical?`<div class="card"><h3>Medical history</h3><div class="tl">${ev.map(e=>`<div class="ev"><div class="d">${e.d} &middot; ${e.t} &middot; ${e.by}</div>${e.x}</div>`).join('')||'<p class="muted">No visits yet.</p>'}</div></div>`:'<div class="card muted">Clinical notes are hidden for the Cashier role. Only billing is visible.</div>'}
<div class="card"><h3>Bills</h3>${b.map(billRow).join('')||'<p class="muted">No bills.</p>'}</div>`};
function vitals(){modal(`<h3>Record vitals</h3><div class="row"><div><label>BP</label><input id="bp" value="120/80"></div><div><label>Temp °C</label><input id="tp" value="36.9"></div></div><div class="row"><div><label>Pulse</label><input id="pl" value="76"></div><div><label>Weight kg</label><input id="wt" value="70"></div></div><label>Nursing note</label><textarea id="nn" rows="2" placeholder="Optional"></textarea><div class="row" style="margin-top:12px"><button class="btn" onclick="saveV()">Save</button><button class="btn sec" onclick="close_()">Cancel</button></div>`)}
function saveV(){const p=pt(cur);p.events.push({d:today,t:'Vitals',x:`BP ${$('#bp').value}, Temp ${$('#tp').value}°C, Pulse ${$('#pl').value}, Wt ${$('#wt').value}kg${$('#nn').value?'. '+$('#nn').value:''}`,by:WHO[role]});log('Recorded vitals for '+p.id);close_();render();toast('Vitals saved. The doctor sees them immediately.')}
function consult(){modal(`<h3>Consultation note</h3><label>Complaint & findings</label><textarea id="cn" rows="3" placeholder="e.g. Fever 3 days, headache..."></textarea><label>Diagnosis</label><input id="dx" placeholder="e.g. Malaria"><label>Bill for</label><select id="ct"><option>Consultation (GP)</option><option>Consultation (Specialist)</option></select><div class="row" style="margin-top:12px"><button class="btn" onclick="saveC()">Save</button><button class="btn sec" onclick="close_()">Cancel</button></div>`)}
function saveC(){const p=pt(cur),ct=$('#ct').value;p.events.push({d:today,t:'Consultation',x:($('#dx').value?'<b>'+$('#dx').value+'</b>. ':'')+$('#cn').value,by:WHO[role]});addBill(p.id,ct,S.prices[ct]);log('Consultation note for '+p.id);close_();render();toast('Note saved and '+ct+' added to the bill automatically.')}
function labreq(){modal(`<h3>Request lab test</h3><select id="lt">${['Malaria parasite test','Full blood count','Lipid profile','Urinalysis'].map(t=>`<option>${t}</option>`).join('')}</select><div class="row" style="margin-top:12px"><button class="btn" onclick="saveL()">Send to lab</button><button class="btn sec" onclick="close_()">Cancel</button></div>`)}
function saveL(){const t=$('#lt').value;S.labs.push({id:Date.now(),pid:cur,test:t,status:'Pending',res:'',d:today});addBill(cur,t,S.prices[t]);log('Lab request '+t+' for '+cur);close_();render();toast('Sent to the lab and billed. No paper form needed.')}
function presc(){const p=pt(cur);modal(`<h3>Prescribe</h3><select id="dr">${S.stock.map(s=>`<option>${s.drug}</option>`).join('')}</select><label>Quantity</label><input id="dq" type="number" value="10"><div id="aw"></div><div class="row" style="margin-top:12px"><button class="btn" onclick="saveR()">Send to pharmacy</button><button class="btn sec" onclick="close_()">Cancel</button></div>`);
$('#dr').onchange=()=>{const d=$('#dr').value;$('#aw').innerHTML=(p.allergies.includes('Penicillin')&&/amoxicillin/i.test(d))?'<div class="allergy">&#9888; Warning: '+p.name+' is allergic to Penicillin. Amoxicillin is a penicillin.</div>':''}}
function saveR(){const d=$('#dr').value;S.rx.push({id:Date.now(),pid:cur,drug:d,qty:+$('#dq').value,status:'To dispense',d:today});pt(cur).events.push({d:today,t:'Prescription',x:d+' x'+$('#dq').value,by:WHO[role]});log('Prescribed '+d+' for '+cur);close_();render();toast('Prescription is now on the pharmacy screen.')}
V.reg=()=>`<button class="btn sm sec" onclick="go('patients')">&larr; Back</button><div class="card" style="margin-top:10px"><h2>Register new patient</h2>
<label>Full name</label><input id="rn" placeholder="Surname first name"><div class="row"><div><label>Phone (WhatsApp)</label><input id="rp" placeholder="080..."></div><div><label>Sex</label><select id="rs"><option>F</option><option>M</option></select></div></div>
<div class="row"><div><label>Date of birth</label><input id="rd" type="date" value="1990-01-01"></div><div><label>Blood group</label><select id="rb"><option>Unknown</option><option>O+</option><option>O-</option><option>A+</option><option>B+</option><option>AB+</option></select></div></div>
<label>Known allergies (comma separated)</label><input id="ra" placeholder="e.g. Penicillin"><label>HMO / insurance (if any)</label><input id="rh" placeholder="Leave blank if self-paying"><label>Next of kin & phone</label><input id="rk">
<label style="display:flex;gap:8px;align-items:flex-start;color:var(--ink)"><input type="checkbox" id="rc" style="width:auto" checked> Patient consents to the hospital storing their records and sending appointment and result updates on WhatsApp.</label>
<button class="btn" style="margin-top:12px;width:100%" onclick="saveReg()">Register and bill card fee</button></div>`;
function saveReg(){const n=$('#rn').value.trim();if(!n)return toast('Enter the patient name.');if(!$('#rc').checked)return toast('Consent is required before storing records.');const id='DSH-'+(++S.seq);
S.patients.push({id,name:n,phone:$('#rp').value||'08000000000',sex:$('#rs').value,dob:$('#rd').value,blood:$('#rb').value,allergies:$('#ra').value?$('#ra').value.split(',').map(s=>s.trim()):[],hmo:$('#rh').value,nok:$('#rk').value||'Not given',consent:true,events:[]});
addBill(id,'Registration & card',S.prices['Registration & card']);wa(id,`Welcome to ${HN}, ${n.split(' ')[0]}. Your hospital number is ${id}. Keep this message; you will not need a paper card.`);log('Registered new patient '+id);toast('Registered as '+id+'. Welcome message sent on WhatsApp.');go('pt',id)}
V.appts=()=>{const l=[...S.appts].sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));const st=['Booked','Waiting','With doctor','Done'];
return `<h2>Appointments & queue</h2><div class="card"><div class="list">${l.map(a=>`<div class="it"><div><div class="t">${a.date==today?'Today':a.date} ${a.time} &middot; ${pt(a.pid).name}</div><div class="s">${a.clinic} &middot; ${a.doc}</div></div><select style="width:auto" onchange="setA(${a.id},this.value)">${st.map(s=>`<option ${s==a.status?'selected':''}>${s}</option>`).join('')}</select></div>`).join('')}</div></div><button class="btn" onclick="book()">+ Book appointment</button>`};
function setA(id,s){const a=S.appts.find(x=>x.id==id);a.status=s;log('Queue: '+pt(a.pid).name+' '+s);save();render()}
function book(pid){modal(`<h3>Book appointment</h3><label>Patient</label><select id="bp_">${S.patients.map(p=>`<option value="${p.id}" ${p.id==pid?'selected':''}>${p.name} (${p.id})</option>`).join('')}</select><div class="row"><div><label>Date</label><input id="bd" type="date" value="${today}"></div><div><label>Time</label><input id="bt" type="time" value="14:00"></div></div><label>Clinic</label><select id="bc"><option>General OPD</option><option>Antenatal</option><option>Paediatrics</option><option>Surgery</option></select><label>Doctor</label><select id="bdoc"><option>Dr. Ibe</option><option>Dr. Amadi</option></select><div class="row" style="margin-top:12px"><button class="btn" onclick="saveB()">Book & send WhatsApp reminder</button></div>`)}
function saveB(){const a={id:Date.now(),pid:$('#bp_').value,date:$('#bd').value,time:$('#bt').value,clinic:$('#bc').value,doc:$('#bdoc').value,status:'Booked'};S.appts.push(a);const p=pt(a.pid);wa(p.id,`Hello ${p.name.split(' ')[0]}, your ${a.clinic} appointment at ${HN} is booked for ${a.date} at ${a.time} with ${a.doc}.\nWe will remind you the day before. Reply 2 to reschedule.`);log('Booked appointment for '+p.id);close_();render();toast('Booked. Reminder sent to '+p.phone+' on WhatsApp.')}
V.lab=()=>`<h2>Laboratory</h2><div class="card"><h3>Pending requests</h3><div class="list">${S.labs.filter(l=>l.status=='Pending').map(l=>`<div class="it"><div><div class="t">${l.test}</div><div class="s">${pt(l.pid).name} &middot; ${l.pid} &middot; requested ${l.d}</div></div><button class="btn sm" onclick="res(${l.id})">Enter result</button></div>`).join('')||'<p class="muted">All clear.</p>'}</div></div>
<div class="card"><h3>Completed</h3><div class="list">${S.labs.filter(l=>l.status!='Pending').map(l=>`<div class="it"><div><div class="t">${l.test}: ${l.res}</div><div class="s">${pt(l.pid).name} &middot; ${l.d}</div></div><span class="tag grn">Released</span></div>`).join('')||'<p class="muted">None yet.</p>'}</div></div>`;
function res(id){modal(`<h3>Enter result</h3><textarea id="rv" rows="3" placeholder="e.g. Total cholesterol 5.8 mmol/L (high)"></textarea><div class="row" style="margin-top:12px"><button class="btn" onclick="saveRes(${id})">Release to doctor & notify patient</button></div>`)}
function saveRes(id){const l=S.labs.find(x=>x.id==id),p=pt(l.pid);l.res=$('#rv').value||'Within normal limits';l.status='Done';p.events.push({d:today,t:'Lab',x:l.test+': '+l.res,by:WHO[role]});wa(p.id,`Hello ${p.name.split(' ')[0]}, your ${l.test} result is ready at ${HN}. Please see your doctor at your next visit or reply 1 to book a review.`);log('Released '+l.test+' for '+p.id);close_();render();toast('Result is in the patient record and the patient was told on WhatsApp.')}
V.pharm=()=>`<h2>Pharmacy</h2><div class="card"><h3>Prescriptions to dispense</h3><div class="list">${S.rx.filter(r=>r.status=='To dispense').map(r=>`<div class="it"><div><div class="t">${r.drug} x${r.qty}</div><div class="s">${pt(r.pid).name} &middot; ${r.pid}</div></div><button class="btn sm" onclick="disp(${r.id})">Dispense & bill</button></div>`).join('')||'<p class="muted">Nothing waiting.</p>'}</div></div>
<div class="card"><h3>Drug stock</h3><table><tr><th>Drug</th><th>Qty</th><th>Expiry</th></tr>${S.stock.map(s=>`<tr><td>${s.drug}</td><td>${s.qty<30?`<span class="tag red">${s.qty} low</span>`:s.qty}</td><td>${dleft(s.exp)<60?`<span class="tag amb">${dleft(s.exp)} days</span>`:s.exp}</td></tr>`).join('')}</table></div>`;
function disp(id){const r=S.rx.find(x=>x.id==id),s=S.stock.find(x=>x.drug==r.drug);if(s){if(s.qty<r.qty)return toast('Not enough stock.');s.qty-=r.qty;addBill(r.pid,r.drug+' x'+r.qty,s.price*r.qty)}r.status='Dispensed';log('Dispensed '+r.drug+' to '+r.pid);render();toast('Dispensed. Stock reduced and drug added to the bill.')}
function addBill(pid,item,amt){let b=S.bills.find(x=>x.pid==pid&&x.d==today&&x.paid<tot(x));if(!b){b={no:'INV-'+(++S.inv),pid,items:[],paid:0,method:'',d:today,hmo:!!pt(pid).hmo};S.bills.push(b)}b.items.push([item,amt]);save()}
function billRow(b){const t=tot(b),bal=t-b.paid;return `<div class="it"><div><div class="t">${b.no} &middot; ${pt(b.pid).name} ${b.hmo?'<span class="tag acc">HMO</span>':''}</div><div class="s">${b.items.map(i=>i[0]+' '+N(i[1])).join(' &middot; ')}</div><div class="s">${b.d} &middot; Total ${N(t)}${b.paid?' &middot; Paid '+N(b.paid)+' ('+b.method+')':''}</div></div>${bal>0?`<div class="row" style="flex:0 0 auto"><span class="tag red">${N(bal)} due</span>${['Cashier','Admin','Records officer'].includes(role)?`<button class="btn sm" onclick="cash('${b.no}')">Cash / POS</button><button class="btn sm sec" onclick="link('${b.no}')">Send pay link</button>`:''}</div>`:'<span class="tag grn">Paid</span>'}</div>`}
V.bill=()=>{const due=S.bills.filter(b=>tot(b)>b.paid),pd=S.bills.filter(b=>tot(b)<=b.paid);return `<h2>Billing & payments</h2><div class="grid"><div class="kpi"><b>${N(due.reduce((a,b)=>a+tot(b)-b.paid,0))}</b><span>Outstanding</span></div><div class="kpi"><b>${N(S.bills.filter(b=>b.d==today).reduce((a,b)=>a+b.paid,0))}</b><span>Collected today</span></div><div class="kpi"><b>${pd.filter(b=>/Online/.test(b.method)).length}</b><span>Paid online</span></div></div>
<div class="card" style="margin-top:12px"><h3>Unpaid bills</h3><div class="list">${due.map(billRow).join('')||'<p class="muted">Nothing outstanding.</p>'}</div></div><div class="card"><h3>Paid</h3><div class="list">${pd.map(billRow).join('')}</div></div>
<div class="card"><h3>Price list</h3><table>${Object.entries(S.prices).map(([k,v])=>`<tr><td>${k}</td><td>${N(v)}</td></tr>`).join('')}</table><p class="muted">Every service, test and drug is billed the moment it is ordered, so nothing is given free by mistake.</p></div>`};
function pay(no,method){const b=S.bills.find(x=>x.no==no);b.paid=tot(b);b.method=method;const p=pt(b.pid);wa(p.id,`Payment received: ${N(tot(b))} for ${b.no} at ${HN}. Thank you, ${p.name.split(' ')[0]}.`);log('Payment '+b.no+' '+method);save()}
function cash(no){modal(`<h3>Record payment</h3><p>${no}</p><div class="row"><button class="btn" onclick="pay('${no}','Cash');close_();render();toast('Receipt sent to the patient on WhatsApp.')">Cash</button><button class="btn" onclick="pay('${no}','POS');close_();render();toast('Receipt sent to the patient on WhatsApp.')">POS</button></div>`)}
function link(no){const b=S.bills.find(x=>x.no==no),p=pt(b.pid);wa(p.id,`Hello ${p.name.split(' ')[0]}, your bill ${no} at ${HN} is ${N(tot(b)-b.paid)}.\nPay securely by card, transfer or USSD: ${location.origin+location.pathname.replace(/index\.html$/,'')}site.html#pay=${no}`);log('Sent payment link '+no);render();toast('Payment link sent on WhatsApp. Open WhatsApp messages to try it as the patient.')}
V.wa=()=>`<h2>WhatsApp messages sent</h2><p class="muted">What patients receive on their phones. In the real system these go out automatically through the WhatsApp Business platform.</p><div class="phone"><div class="top">${HN}<small>Business account</small></div><div class="msgs">${S.wa.map(m=>`<div class="bub"><b>To ${pt(m.to).name}</b>\n${m.msg.replace(/(https?:\/\/\S+)/g,'<a href="$1" target="_blank">$1</a>')}<div class="tm">${m.t}</div></div>`).join('')}</div></div>`;
V.audit=()=>`<h2>Audit log</h2><p class="muted">Every record opened or changed, by whom and when. This is the evidence the Nigeria Data Protection Act expects the hospital to keep.</p><div class="card"><table><tr><th>Time</th><th>Who</th><th>Action</th></tr>${S.audit.slice(0,60).map(a=>`<tr><td>${a.t}</td><td>${a.who}</td><td>${a.a}</td></tr>`).join('')}</table></div>`;
if(!ROLES[role].includes(view))view=ROLES[role][0];$('#sitelink').href='site.html'+(P.get('h')?'?h='+encodeURIComponent(HN):'');render();
